name: BTC_Price_Test
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  btc:
    runs-on: ubuntu-latest
    steps:
      - name: Send BTC Price
        run: |
          $BTC_PRICE = (curl -s https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT | jq -r .price)
          $MESSAGE = "₿ BTC Price: $$BTC_PRICE"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.CHAT_ID }} -d text="$MESSAGE"
